volumes:
  bancoplatinum_data: {}
  bancoplatinum_jenkins: {}
  bancoplatinum_jfrog: {}
  bancoplatinum_pgdata: {}

services:
  # app:
  #   build:
  #     context: ./ctacorriente
  #     dockerfile: Dockerfile
  #     args:
  #       PROFILE: ${SPRING_PROFILES_ACTIVE}
  #   restart: always
  #   ports:
  #     - 8001:8001
  #   volumes:
  #     - ./ctacorriente:/app:z
  #   depends_on:
  #     - bancoplatinum_db
  #   env_file:
  #     - .env
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=default
  #   networks:
  #     - bancoplatinum_network
  
  # bancoplatinum_db:
  #   image: mysql:8.4.0
  #   restart: always
  #   env_file:
  #     - .env
  #   volumes:
  #     - bancoplatinum_data:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: ${DB_NAME}
  #     MYSQL_USER: ${DB_USER}
  #     MYSQL_PASSWORD: ${DB_PASSWORD}
  #     MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
  #   ports:
  #     - 3307:3306
  #   networks:
  #     - bancoplatinum_network
  # bancoplatinum_jenkins:
  #   build:
  #     context: .
  #     dockerfile: jenkins/Dockerfile
  #   image: bancoplatinum_jenkins
  #   container_name: bancoplatinum_jenkins
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   restart: on-failure
  #   volumes:
  #     - bancoplatinum_jenkins:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - bancoplatinum_network

  bancoplatinum_postgres:
    image: postgres:13
    container_name: bancoplatinum_artifactory_postgres
    environment:
      POSTGRES_USER: artifactory
      POSTGRES_PASSWORD: password
      POSTGRES_DB: artifactory
    volumes:
      - bancoplatinum_pgdata:/var/lib/postgresql/data
    networks:
      - bancoplatinum_network

  bancoplatinum_jfrog_artifactory:
    image: releases-docker.jfrog.io/jfrog/artifactory-oss:7.77.5
    ports:
      - 8081:8081
      - 8082:8082
    container_name: bancoplatinum_jfrog_artifactory
    environment:
      - JAVA_OPTIONS=-Dartifactory.jdbc.driver=org.postgresql.Driver -Dartifactory.jdbc.url=jdbc:postgresql://artifactory_postgres:5432/artifactory -Dartifactory.jdbc.user=artifactory -Dartifactory.jdbc.password=password
    depends_on:
      - bancoplatinum_postgres
    volumes:
      - bancoplatinum_jfrog:/var/opt/jfrog/artifactory
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
    networks:
      - bancoplatinum_network

networks:
  bancoplatinum_network:
    driver: bridge
